# Generated by Django 2.1.5 on 2019-01-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190126_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver_id',
            field=models.IntegerField(default='0', max_length=1000),
        ),
    ]
