# Generated by Django 2.1.5 on 2019-01-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userinfo_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='username',
            new_name='name',
        ),
    ]
