# Generated by Django 2.1.5 on 2019-01-27 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_remove_userinfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='user',
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger_id',
            field=models.IntegerField(default='0'),
        ),
    ]
