# Generated by Django 2.1.5 on 2019-01-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190127_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='passenger',
            new_name='user',
        ),
    ]
